/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LoginOtpRouteImport } from './routes/login/otp'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPingserverRouteImport } from './routes/demo/pingserver'
import { Route as DashboardAdminpanelRouteImport } from './routes/dashboard/adminpanel'
import { Route as DashboardAddRouteImport } from './routes/dashboard/add'
import { Route as DashboardAktaCompanyIdRouteImport } from './routes/dashboard/akta/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPingserverRoute = DemoPingserverRouteImport.update({
  id: '/demo/pingserver',
  path: '/demo/pingserver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminpanelRoute = DashboardAdminpanelRouteImport.update({
  id: '/dashboard/adminpanel',
  path: '/dashboard/adminpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddRoute = DashboardAddRouteImport.update({
  id: '/dashboard/add',
  path: '/dashboard/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAktaCompanyIdRoute = DashboardAktaCompanyIdRouteImport.update({
  id: '/dashboard/akta/$companyId',
  path: '/dashboard/akta/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/adminpanel': typeof DashboardAdminpanelRoute
  '/demo/pingserver': typeof DemoPingserverRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/otp': typeof LoginOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/akta/$companyId': typeof DashboardAktaCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/adminpanel': typeof DashboardAdminpanelRoute
  '/demo/pingserver': typeof DemoPingserverRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/otp': typeof LoginOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/dashboard/akta/$companyId': typeof DashboardAktaCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/add': typeof DashboardAddRoute
  '/dashboard/adminpanel': typeof DashboardAdminpanelRoute
  '/demo/pingserver': typeof DemoPingserverRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/login/otp': typeof LoginOtpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/dashboard/akta/$companyId': typeof DashboardAktaCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/add'
    | '/dashboard/adminpanel'
    | '/demo/pingserver'
    | '/demo/tanstack-query'
    | '/login/otp'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/dashboard/akta/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/add'
    | '/dashboard/adminpanel'
    | '/demo/pingserver'
    | '/demo/tanstack-query'
    | '/login/otp'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/dashboard/akta/$companyId'
  id:
    | '__root__'
    | '/'
    | '/dashboard/add'
    | '/dashboard/adminpanel'
    | '/demo/pingserver'
    | '/demo/tanstack-query'
    | '/login/otp'
    | '/dashboard/'
    | '/login/'
    | '/profile/'
    | '/dashboard/akta/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAddRoute: typeof DashboardAddRoute
  DashboardAdminpanelRoute: typeof DashboardAdminpanelRoute
  DemoPingserverRoute: typeof DemoPingserverRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  LoginOtpRoute: typeof LoginOtpRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  DashboardAktaCompanyIdRoute: typeof DashboardAktaCompanyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pingserver': {
      id: '/demo/pingserver'
      path: '/demo/pingserver'
      fullPath: '/demo/pingserver'
      preLoaderRoute: typeof DemoPingserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/adminpanel': {
      id: '/dashboard/adminpanel'
      path: '/dashboard/adminpanel'
      fullPath: '/dashboard/adminpanel'
      preLoaderRoute: typeof DashboardAdminpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/add': {
      id: '/dashboard/add'
      path: '/dashboard/add'
      fullPath: '/dashboard/add'
      preLoaderRoute: typeof DashboardAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/akta/$companyId': {
      id: '/dashboard/akta/$companyId'
      path: '/dashboard/akta/$companyId'
      fullPath: '/dashboard/akta/$companyId'
      preLoaderRoute: typeof DashboardAktaCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAddRoute: DashboardAddRoute,
  DashboardAdminpanelRoute: DashboardAdminpanelRoute,
  DemoPingserverRoute: DemoPingserverRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  LoginOtpRoute: LoginOtpRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  DashboardAktaCompanyIdRoute: DashboardAktaCompanyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
